### ISSUE TITLE
Replace Scalariform with Scalafmt

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt-houserules#15]
- https://github.com/sbt/sbt/pull/3125
- https://github.com/sbt/zinc/pull/294
- https://github.com/sbt/librarymanagement/pull/87

Currently sbt-houserule is pulling in Scalariform, which we no longer use.

**Comment by dwijnand** [comment]
fixed as a part of https://github.com/sbt/sbt-houserules/pull/18.
