### ISSUE TITLE
release 0.3.4 to get sbt-bintray upgrade out there

### ISSUE THREAD

**Issue by SethTisue** [sbt/sbt-houserules#17]
may I suggest a 0.3.4 release to get the sbt-bintray 0.4.0 -> 0.5.1 upgrade out there?

context: sbt-bintray 0.5.1 has been found to work with dbuild, so I'm (over at https://github.com/scala/community-builds/issues/591) trying to unfork projects in the Scala community build we had forked because dbuild and bintray were fighting. to do this work, it's better if everybody is on 0.5.1 and I don't have to think about possible 0.4.0 vs 0.5.1 differences

**Comment by SethTisue** [comment]
P.S. note that the version number in README.md is behind reality

**Comment by eed3si9n** [comment]
The back published 0.3.3 already has what you want, I think.

```xml
	<dependencies>
		<dependency org="org.scala-lang" name="scala-compiler" rev="2.12.2" conf="scala-tool->default,optional(default)"/>
		<dependency org="org.scala-lang" name="scala-library" rev="2.12.2" conf="scala-tool->default,optional(default);provided->default(compile)"/>
		<dependency org="org.scala-sbt" name="sbt" rev="1.0.0-RC2" conf="provided->default(compile)"/>
		<dependency org="com.typesafe.sbt" name="sbt-git" rev="0.9.3" conf="compile->default(compile)" e:sbtVersion="1.0" e:scalaVersion="2.12"/>
		<dependency org="org.foundweekends" name="sbt-bintray" rev="0.5.1" conf="compile->default(compile)" e:sbtVersion="1.0" e:scalaVersion="2.12"/>
		<dependency org="com.jsuereth" name="sbt-pgp" rev="1.1.0-M1" conf="compile->default(compile)" e:sbtVersion="1.0" e:scalaVersion="2.12"/>
	</dependencies>
```

**Comment by SethTisue** [comment]
@eed3si9n with sbt-houserules 0.3.3 I'm getting sbt-bintray 0.4.0, not 0.5.1

you can reproduce the problem in the sbt/sbinary repo, where despite https://github.com/sbt/sbinary/pull/8 being merged, `reload plugins` followed by `show fullClasspath` shows `[info] * Attributed(/Users/tisue/.ivy2/cache/scala_2.10/sbt_0.13/org.foundweekends/sbt-bintray/jars/sbt-bintray-0.4.0.jar)`

**Comment by eed3si9n** [comment]
Oh you mean for sbt 0.13. Then you're right.

**Comment by dwijnand** [comment]
https://github.com/sbt/sbt-houserules/releases/tag/v0.3.4

**Comment by SethTisue** [comment]
thank you Dale!
